In [1]:
lst = []
print(type(lst))

<class 'list'>


In [5]:
lst = []
for i in range(1,21):
    lst.append(i)
print(lst)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


In [11]:
print(lst[:5])
print(lst[-6:])
print(lst[5:16])

[1, 2, 3, 4, 5]
[15, 16, 17, 18, 19, 20]
[6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]


In [12]:
lst2 = []
for i in range(10):
    lst2.append(i**2)
print(lst2)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [6]:
print(lst[0])
print(lst[10])
print(lst[-1])

1
11
20


In [1]:
fruits = ["apple", "banana", "cherry"]  
for fruit in fruits:
    print(fruit)

apple
banana
cherry


In [14]:
my_empty_set = set([1,2,3,4,5])
print(my_empty_set)

{1, 2, 3, 4, 5}


In [15]:
my_empty_set.add(6)
print(my_empty_set)

{1, 2, 3, 4, 5, 6}


In [16]:
students  = {"name": "John", "age": 25, "courses": ["Math", "CompSci"]}
print(students)

{'name': 'John', 'age': 25, 'courses': ['Math', 'CompSci']}


In [18]:
print(students["name"])
print(students.get("age"))

John
25


In [19]:
for keys in students.keys():
        print(keys)

name
age
courses


In [20]:
evens ={x:x**2 for x in range(10) if x%2==0}
print(evens)

{0: 0, 2: 4, 4: 16, 6: 36, 8: 64}


In [38]:
iterator = iter(fruits)
next(iterator)

'apple'

In [46]:
lst = [1, 2, 3, 4, 5]

In [47]:
iterator = iter(lst)
print(next(iterator))

1


In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
print(arr1) 

[1 2 3 4 5]


In [3]:
arr2 = np.array([1,2,3,4,5,6])
arr2 = arr2.reshape(2,3)
print(arr2)

[[1 2 3]
 [4 5 6]]


In [8]:
np.arange(0, 10, 2).reshape(5, 1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [9]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
#numpy vectorwise operation
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([4,5,6,7,8,])

#element wise addition
print(arr1 + arr2)

#Element wise subtraction
print(arr1 - arr2)

[ 5  7  9 11 13]
[-3 -3 -3 -3 -3]


In [13]:
#Unioversal Function
#array slicing and indexing
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]]) 
print(arr[0,1])

2


In [14]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [15]:
### Stastical concepts normalisation
mean = np.mean(arr)
std = np.std(arr)
normalised_arr = (arr - mean) / std
print(normalised_arr)

[[-1.5666989  -1.21854359 -0.87038828 -0.52223297 -0.17407766]
 [ 0.17407766  0.52223297  0.87038828  1.21854359  1.5666989 ]]
